


# application-dev.yml
server:
  port: 8083

spring:
  application:
    name: AI-SERVICE

  data:
    mongodb:
      uri: mongodb://localhost:27017/recommendations


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
